# Generated by Django 5.2.13 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityevent',
            options={'ordering': ['date', 'time', 'id'], 'verbose_name': 'community event', 'verbose_name_plural': 'community events'},
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='category',
            field=models.CharField(choices=[('saude', 'Health'), ('educacao', 'Education'), ('cultura', 'Culture'), ('assistencia_social', 'Social assistance'), ('comercio', 'Commerce'), ('data_comemorativa', 'Commemorative date')], default='cultura', max_length=32, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='highlighted'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='time',
            field=models.CharField(blank=True, max_length=64, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
