# Generated by Django 5.2.13 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcampaign',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'donation campaign', 'verbose_name_plural': 'donation campaigns'},
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='collection_points',
            field=models.JSONField(default=list, help_text='List of objects: [{"name": "...", "address": "...", "hours": "..."}]', verbose_name='collection points'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='donation_type',
            field=models.CharField(choices=[('roupas', 'Clothing'), ('alimentos', 'Food'), ('brinquedos', 'Toys'), ('moveis', 'Furniture'), ('medicamentos', 'Medicine'), ('outros', 'Other')], default='outros', max_length=32, verbose_name='donation type'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='goal',
            field=models.CharField(blank=True, max_length=255, verbose_name='goal (free text)'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
