"""
Corrige bases onde 0001_initial antigo não criou a tabela no PostgreSQL,
mas django_migrations já marca 0001/0002 como aplicadas — evita falha em 0003.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_donationcampaign_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS community_donationcampaign (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title varchar(200) NOT NULL,
                description text NOT NULL DEFAULT '',
                donation_type varchar(32) NOT NULL DEFAULT 'outros',
                is_active boolean NOT NULL DEFAULT true,
                goal varchar(255) NOT NULL DEFAULT '',
                collection_points jsonb NOT NULL DEFAULT '[]'::jsonb,
                created_at timestamptz NOT NULL DEFAULT NOW(),
                updated_at timestamptz NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS community_donationcampaign_is_active_idx
                ON community_donationcampaign (is_active);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
