# Generated by Django 5.2.13 on 2026-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationcampaign_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcampaign',
            name='goal',
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='goal_target',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric collection target (e.g. number of pieces, baskets).', null=True, verbose_name='goal target'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='goal_unit',
            field=models.CharField(blank=True, help_text='Unit label shown after the number, e.g. "peças", "cestas", "brinquedos".', max_length=64, verbose_name='goal unit'),
        ),
    ]
