# Generated by Django 5.2.13 on 2026-04-26 15:02 — reordered to preserve data.

import django.db.models.deletion
from django.db import migrations, models


def copy_point_links_from_legacy_fk(apps, schema_editor):
    """Each old row in donationcollectionpoint was tied to one campaign; create a link row."""
    DonationCampaignPointLink = apps.get_model("donations", "DonationCampaignPointLink")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT campaign_id, id, sort_order
            FROM community_donationcollectionpoint
            WHERE campaign_id IS NOT NULL
            """
        )
        rows = cursor.fetchall()
    for campaign_id, point_id, sort_order in rows:
        DonationCampaignPointLink.objects.create(
            campaign_id=campaign_id,
            collection_point_id=point_id,
            sort_order=sort_order or 0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_collection_points_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationcollectionpoint",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "donation collection point",
                "verbose_name_plural": "donation collection points",
            },
        ),
        migrations.CreateModel(
            name="DonationCampaignPointLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Lower values appear first for this campaign.",
                        verbose_name="display order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_links",
                        to="donations.donationcampaign",
                        verbose_name="campaign",
                    ),
                ),
                (
                    "collection_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_links",
                        to="donations.donationcollectionpoint",
                        verbose_name="collection point",
                    ),
                ),
            ],
            options={
                "verbose_name": "donation campaign collection link",
                "verbose_name_plural": "donation campaign collection links",
                "db_table": "community_donationcampaignpointlink",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(copy_point_links_from_legacy_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="donationcollectionpoint",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="donationcollectionpoint",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="collection_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="donation_campaigns",
                through="donations.DonationCampaignPointLink",
                to="donations.donationcollectionpoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="donationcampaignpointlink",
            constraint=models.UniqueConstraint(
                fields=("campaign", "collection_point"),
                name="uniq_donation_campaign_collection_point",
            ),
        ),
    ]
