# Generated by Django 5.2.13 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitysuggestion',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'suggestion', 'verbose_name_plural': 'suggestions'},
        ),
        migrations.AlterField(
            model_name='communitysuggestion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='communitysuggestion',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='communitysuggestion',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='communitysuggestion',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='reviewed'),
        ),
        migrations.AlterField(
            model_name='communitysuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('evento', 'Suggest event'), ('informacao', 'Send information'), ('foto', 'Share photo')], max_length=32, verbose_name='type'),
        ),
    ]
