# Generated by Django 5.2.13 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitynews',
            options={'ordering': ['-is_pinned', '-created_at', 'id'], 'verbose_name': 'news item', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='communitynews',
            name='category',
            field=models.CharField(choices=[('aviso', 'Notice'), ('comunicado', 'Announcement'), ('atualizacao', 'Update')], default='comunicado', max_length=32),
        ),
        migrations.AlterField(
            model_name='communitynews',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='communitynews',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='pinned'),
        ),
        migrations.AlterField(
            model_name='communitynews',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
