# Generated by Django 5.2.13 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefulcontact',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'useful contact', 'verbose_name_plural': 'useful contacts'},
        ),
        migrations.AlterField(
            model_name='usefulcontact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='usefulcontact',
            name='hours',
            field=models.CharField(max_length=120, verbose_name='opening hours'),
        ),
        migrations.AlterField(
            model_name='usefulcontact',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='usefulcontact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usefulcontact',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='usefulcontact',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='sort order'),
        ),
    ]
