# Generated by Django 5.2.13 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'gallery item', 'verbose_name_plural': 'gallery'},
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(blank=True, max_length=64, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=16),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_url',
            field=models.URLField(max_length=500, verbose_name='media URL'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
