# Generated by Django 5.2.13 on 2026-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('date', models.DateField(verbose_name='data')),
                ('time', models.CharField(blank=True, max_length=64, verbose_name='horário')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='local')),
                ('category', models.CharField(choices=[('saude', 'Saúde'), ('educacao', 'Educação'), ('cultura', 'Cultura'), ('assistencia_social', 'Assistência social'), ('comercio', 'Comércio'), ('data_comemorativa', 'Data comemorativa')], default='cultura', max_length=32, verbose_name='categoria')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evento comunitário',
                'verbose_name_plural': 'eventos comunitários',
                'ordering': ['date', 'time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('category', models.CharField(choices=[('aviso', 'Aviso'), ('comunicado', 'Comunicado'), ('atualizacao', 'Atualização')], default='comunicado', max_length=32)),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='fixado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
                'ordering': ['-is_pinned', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('suggestion_type', models.CharField(choices=[('evento', 'Sugerir evento'), ('informacao', 'Enviar informação'), ('foto', 'Compartilhar foto')], max_length=32, verbose_name='tipo')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(db_index=True, default=False, verbose_name='revisado')),
            ],
            options={
                'verbose_name': 'sugestão',
                'verbose_name_plural': 'sugestões',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('donation_type', models.CharField(choices=[('roupas', 'Roupas'), ('alimentos', 'Alimentos'), ('brinquedos', 'Brinquedos'), ('moveis', 'Móveis'), ('medicamentos', 'Medicamentos'), ('outros', 'Outros')], default='outros', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativa')),
                ('goal', models.CharField(blank=True, max_length=255, verbose_name='meta (texto livre)')),
                ('collection_points', models.JSONField(default=list, help_text='Lista de objetos: [{"name": "...", "address": "...", "hours": "..."}]', verbose_name='pontos de coleta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'campanha de doação',
                'verbose_name_plural': 'campanhas de doação',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='categoria')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=16)),
                ('media_url', models.URLField(max_length=500, verbose_name='URL da mídia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'item da galeria',
                'verbose_name_plural': 'galeria',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsefulContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('phone', models.CharField(max_length=64, verbose_name='telefone')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('hours', models.CharField(max_length=120, verbose_name='horário de atendimento')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'contato útil',
                'verbose_name_plural': 'contatos úteis',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
    ]
